import { useRef, useState } from 'react';
import { Activity, ArrowUpRight, CalendarCheck, Check, Download, Droplets, MapPin, Plus, ScanLine, Sprout, Sun, Upload, Wind } from 'lucide-react';
import type { WeatherBundle } from '../lib/weather';
import { MEASUREMENT_TYPES, mergeFarmRecords, parseFarmRecords, readFarmRecords, validateMeasurement, writeFarmRecords } from '../lib/farmRecords';
import type { FarmMeasurement, FarmRecords, MeasurementKind } from '../lib/farmRecords';
import { exportLocalJson, formatDate, localDateInput, localDateTimeInput, messageOf } from '../lib/deviceUi';
import '../styles/knowledge.css';

export type ServicePage = 'clinic' | 'weather' | 'market' | 'news' | 'advice' | 'farm' | 'livestock';
export default function FarmDashboard({ weather, loading, weatherError, refresh, navigate }: { weather: WeatherBundle | null; loading: boolean; weatherError: string; refresh: () => void; navigate: (page: ServicePage) => void }) {
  const [records, setRecords] = useState(readFarmRecords);
  const [message, setMessage] = useState('');
  const [profileOpen, setProfileOpen] = useState(false);
  const [profile, setProfile] = useState(records.profile);
  const [taskTitle, setTaskTitle] = useState('');
  const [taskDate, setTaskDate] = useState(localDateInput());
  const [measurementOpen, setMeasurementOpen] = useState(false);
  const [kind, setKind] = useState<MeasurementKind>('soil-water');
  const [value, setValue] = useState('');
  const [place, setPlace] = useState('');
  const [instrument, setInstrument] = useState('');
  const [observedAt, setObservedAt] = useState(localDateTimeInput());
  const fileInput = useRef<HTMLInputElement>(null);
  const today = localDateInput();
  const pending = records.tasks.filter(task => !task.completedAt).sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  const stale = weather && (Date.now() - Date.parse(weather.fetchedAt) > 3600_000 || Date.parse(weather.fetchedAt) > Date.now() + 300000 || !!weather.dataTime && (Date.now() - Date.parse(weather.dataTime) > 3600_000 || Date.parse(weather.dataTime) > Date.now() + 300000));
  const usableWeather = weather && !stale && !weatherError ? weather : null;
  const risks = usableWeather ? [usableWeather.current.temp >= 32 ? '高温：检查作物水分、动物通风与饮水。' : '', usableWeather.current.temp <= 5 ? '低温：检查防寒和设施保温。' : '', usableWeather.forecast[0].rain >= 20 ? '降雨预报偏多：提前巡查排水与畜舍干燥。' : '', usableWeather.current.wind >= 35 ? '风速偏大：检查棚膜、支架和室外设施。' : ''].filter(Boolean) : [];
  function save(next: FarmRecords) { try { writeFarmRecords(next); setRecords(next); setMessage('已保存在这台设备。'); } catch (e) { setMessage(messageOf(e)); } }
  function addMeasurement() {
    const entry: FarmMeasurement = { id: crypto.randomUUID(), kind, value: Number(value), place: place.trim(), instrument: instrument.trim(), observedAt: new Date(observedAt).toISOString() };
    if (!value.trim() || !validateMeasurement(entry) || Date.parse(entry.observedAt) > Date.now() + 300000) { setMessage('请核实采样位置、时间与数值范围。'); return; }
    save({ ...records, measurements: [...records.measurements, entry].slice(-1000) }); setMeasurementOpen(false); setValue('');
  }
  async function importBackup(file: File | undefined) {
    if (!file) return;
    try { if (file.size > 512 * 1024) throw new Error('记录文件过大，请选择 512 KB 以内的 JSON 备份。'); const incoming = parseFarmRecords(JSON.parse(await file.text())); save(mergeFarmRecords(records, incoming)); setMessage(`已合并 ${incoming.tasks.length} 项待办与 ${incoming.measurements.length} 条实测记录。`); } catch (e) { setMessage(messageOf(e)); }
    if (fileInput.current) fileInput.current.value = '';
  }
  return <main className="service-view dashboard-view">
    <div className="service-heading"><div><span className="eyebrow">真实农场 · 每日工作台</span><h2>{records.profile.name || '照顾好今天的农场'}</h2><p>{records.profile.production ? `${records.profile.production} · ${records.profile.stage || '阶段未记录'}` : '天气、观察、待办和销售记录，都从真实情况出发。'}</p></div><button className="quiet-button" onClick={() => { setProfile(records.profile); setProfileOpen(true); }}><MapPin size={16} />农场资料</button></div>
    <section className="dashboard-hero"><div><span className="section-kicker">{weather?.location.name || '当前地区'} · 区域天气参考</span><h3>{weather ? `${Math.round(weather.current.temp)}°C` : '等待天气来信'}{weather && <span>空气湿度 {Math.round(weather.current.humidity)}%</span>}</h3><div className="hero-facts"><span><Wind size={15} />{weather ? `${Math.round(weather.current.wind)} km/h` : '—'}</span><span><Droplets size={15} />降水预报{weather ? `（${weather.forecast[0].date.slice(5)}）` : ''} {weather ? `${weather.forecast[0].rain.toFixed(1)} mm` : '—'}</span><span><CalendarCheck size={15} />{pending.filter(t => t.dueDate <= today).length} 项今日待办</span></div><p>{weatherError ? `${weatherError}${weather ? ' 这里显示上次数据。' : ''}` : weather ? `模型时点 ${weather.currentTime?.replace('T', ' ') || formatDate(weather.dataTime || weather.fetchedAt, true)}（${weather.timezone}） · 获取于 ${formatDate(weather.fetchedAt, true)}${stale ? ' · 数据较旧，请刷新' : ''} · Open-Meteo 区域模型，不是田间实测` : '连接后可查看气温、湿度和预报；请检查网络或手动选择地区。'}</p></div><button className="hero-action" onClick={refresh} disabled={loading}><Sun size={19} />{loading ? '更新中' : '更新天气'}</button></section>
    {risks.length > 0 && <div className="field-alert"><Activity size={18} /><div>{risks.map(risk => <p key={risk}>{risk}</p>)}<small>来自当前区域天气与今日预报的检查提醒，不是病害诊断。</small></div></div>}
    <div className="service-shortcuts"><button onClick={() => navigate('clinic')}><ScanLine size={24} /><div><strong>观察不对劲？</strong><span>拍照、视频或语音，保存田间线索</span></div><ArrowUpRight size={18} /></button><button onClick={() => navigate('market')}><Sprout size={24} /><div><strong>种什么、养多少？</strong><span>先看真实订单、成本和市场依据</span></div><ArrowUpRight size={18} /></button></div>
    <div className="dashboard-columns"><section className="service-card"><div className="section-heading"><h3>我的作业待办</h3><span>{pending.length} 项未完成</span></div><form className="task-form" onSubmit={e => { e.preventDefault(); if (!taskTitle.trim()) return; save({ ...records, tasks: [...records.tasks, { id: crypto.randomUUID(), title: taskTitle.trim(), dueDate: taskDate, createdAt: new Date().toISOString() }].slice(-500) }); setTaskTitle(''); }}><input aria-label="新的农场待办" maxLength={200} value={taskTitle} onChange={e => setTaskTitle(e.target.value)} placeholder="例如：检查 2 号畜舍饮水" required /><input aria-label="待办日期" type="date" value={taskDate} onChange={e => setTaskDate(e.target.value)} required /><button className="square-action" type="submit" aria-label="添加待办"><Plus size={19} /></button></form>{pending.length ? <div className="task-list">{pending.slice(0, 12).map(task => <div key={task.id}><button aria-label={`完成：${task.title}`} onClick={() => save({ ...records, tasks: records.tasks.map(t => t.id === task.id ? { ...t, completedAt: new Date().toISOString() } : t) })}><Check size={17} /></button><strong>{task.title}</strong><span className={task.dueDate < today ? 'overdue-date' : ''}>{task.dueDate === today ? '今天' : task.dueDate}</span></div>)}</div> : <div className="small-empty"><CalendarCheck size={25} /><p>记录当天要做的巡田、喂养和销售工作。</p></div>}{records.tasks.some(t => t.completedAt) && <details className="completed-tasks"><summary>已完成 {records.tasks.filter(t => t.completedAt).length} 项</summary>{records.tasks.filter(t => t.completedAt).slice(-10).reverse().map(task => <p key={task.id}><Check size={13} />{task.title}<button onClick={() => save({ ...records, tasks: records.tasks.map(t => { if (t.id !== task.id) return t; const { completedAt: _completed, ...pendingTask } = t; return pendingTask; }) })}>撤销完成</button></p>)}</details>}</section>
    <section className="service-card"><div className="section-heading"><h3>真实测量记录</h3><button className="text-link" onClick={() => { setMessage(''); setMeasurementOpen(true); }}><Plus size={15} />添加实测</button></div>{records.measurements.length ? <div className="measurement-list">{records.measurements.slice(-8).reverse().map(measurement => <article key={measurement.id}><span><Droplets size={17} /></span><div><strong>{MEASUREMENT_TYPES[measurement.kind].label}<b>{measurement.value} {MEASUREMENT_TYPES[measurement.kind].unit}</b></strong><p>{measurement.place} · {formatDate(measurement.observedAt, true)}{measurement.instrument ? ` · ${measurement.instrument}` : ''}</p></div></article>)}</div> : <div className="small-empty"><Droplets size={25} /><p>田间传感器和水质仪读数更接近现场。记录位置、仪器和时间，便于比较。</p></div>}<p className="card-footnote">这些是你输入的实测值；准确性取决于采样、仪器与校准，不采用游戏模拟数据。</p></section></div>
    <div className="backup-strip"><span>真实记录仅保存在本机，请定期备份。</span><button onClick={() => void exportLocalJson({ ...records, exportedAt: new Date().toISOString() }, `fieldletter-farm-${today}.json`).catch(e => setMessage(messageOf(e)))}><Download size={15} />导出备份</button><button onClick={() => fileInput.current?.click()}><Upload size={15} />合并备份</button><input ref={fileInput} hidden type="file" accept="application/json,.json" onChange={e => void importBackup(e.target.files?.[0])} /></div>
    {message && <p className="inline-message" role="status">{message}</p>}
    {profileOpen && <div className="modal-backdrop" onClick={() => setProfileOpen(false)}><section className="service-modal" role="dialog" aria-modal="true" aria-labelledby="farm-profile-title" onClick={e => e.stopPropagation()}><h2 id="farm-profile-title">我的真实农场</h2><form onSubmit={e => { e.preventDefault(); save({ ...records, profile }); setProfileOpen(false); }}><label>农场名称<input maxLength={200} value={profile.name} onChange={e => setProfile({ ...profile, name: e.target.value })} placeholder="你的农场名称" /></label><label>种植 / 养殖品种<input maxLength={200} value={profile.production} onChange={e => setProfile({ ...profile, production: e.target.value })} placeholder="例如：番茄、蛋鸡、草鱼" /></label><label>当前生产阶段<input maxLength={200} value={profile.stage} onChange={e => setProfile({ ...profile, stage: e.target.value })} placeholder="例如：定植后两周 / 育成期" /></label><label>田间环境与管理备注<textarea maxLength={2000} value={profile.notes} onChange={e => setProfile({ ...profile, notes: e.target.value })} placeholder="土壤、品种、棚室、养殖密度、近期管理等" /></label><div className="modal-actions"><button type="button" className="quiet-button" onClick={() => setProfileOpen(false)}>取消</button><button className="solid-button" type="submit">保存农场资料</button></div></form></section></div>}
    {measurementOpen && <div className="modal-backdrop" onClick={() => setMeasurementOpen(false)}><section className="service-modal" role="dialog" aria-modal="true" aria-labelledby="measurement-title" onClick={e => e.stopPropagation()}><h2 id="measurement-title">记录一次实测</h2><form onSubmit={e => { e.preventDefault(); try { addMeasurement(); } catch { setMessage('请输入有效的测量时间。'); } }}><label>测量项目<select value={kind} onChange={e => setKind(e.target.value as MeasurementKind)}>{Object.entries(MEASUREMENT_TYPES).map(([id, definition]) => <option key={id} value={id}>{definition.label}（{definition.unit}）</option>)}</select></label><div className="form-pair"><label>数值（{MEASUREMENT_TYPES[kind].unit}）<input required type="number" step="any" min={MEASUREMENT_TYPES[kind].min} max={MEASUREMENT_TYPES[kind].max} value={value} onChange={e => setValue(e.target.value)} /></label><label>采样时间<input required type="datetime-local" value={observedAt} onChange={e => setObservedAt(e.target.value)} /></label></div><label>位置 / 深度<input required maxLength={200} value={place} onChange={e => setPlace(e.target.value)} placeholder="例如：北棚根区 20 cm / 1 号池" /></label><label>仪器或检测方法<input maxLength={200} value={instrument} onChange={e => setInstrument(e.target.value)} placeholder="例如：已校准的土壤传感器" /></label>{message && <p className="inline-message" role="status">{message}</p>}<p className="card-footnote">不要把空气湿度填成土壤含水率，或用空气气温代替水温。</p><div className="modal-actions"><button className="quiet-button" type="button" onClick={() => setMeasurementOpen(false)}>取消</button><button className="solid-button" type="submit">保存实测记录</button></div></form></section></div>}
  </main>;
}
